name: Build

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Run local tests
        run: ./gradlew :kace-compiler:test

      - name: Publish To Local
        run: ./gradlew publishToMavenLocal -PVERSION_NAME=0.0.0-SNAPSHOT

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Check spotless
        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

      - name: Test AGP compatibility
        run: chmod +x ./test_agp.sh && ./test_agp.sh
